### ISSUE TITLE
Toys do not appear.  

### ISSUE THREAD

**Issue by OVini72** [leandroeblandi/LateAtNight#4]
When the game starts, the toys to avoid do not appear.

**Comment by leandroeblandi** [comment]
Problema com a Função de Brinquedos
O problema com as funções de brinquedos no seu código está na lógica de desenhar e detectar os brinquedos pisados. Especificamente, a lógica para esconder os brinquedos não pisados e destacar os brinquedos pisados não está funcionando como esperado.

A Fazer:
Corrigir a geração de brinquedos para garantir que estejam dentro dos limites da tela.
Lidar corretamente com o desenho e a detecção de colisão dos brinquedos.
Manter um tratamento consistente dos estados dos brinquedos durante o loop do jogo.
Explicação das Mudanças:
Geração de Brinquedos: Brinquedos agora são gerados dentro de uma margem segura (10 pixels de cada borda) para garantir que não sejam colocados na borda onde o jogador pode não conseguir alcançá-los.
Desenho dos Brinquedos: Se o jogador alcançou o interruptor, todos os brinquedos são exibidos em suas cores. Caso contrário, os brinquedos que o jogador pisou são destacados, e a detecção é ajustada para verificar a proximidade do jogador ao brinquedo.
Colisão com Brinquedos: A detecção de colisão garante que, quando o jogador estiver a 3 pixels de um brinquedo, ele seja considerado pisado. Esse valor pode ser ajustado com base no tamanho e velocidade do jogador.
